### ISSUE TITLE
Discord Invite Has Expired

### ISSUE THREAD

**Issue by padkinsdev** [Member1221/peakterf-frontend#1]
This should be platform-independent, but the discord [invite](https://peakterf.com/submit) has expired.
![photo](https://faebotwebsite.s3.amazonaws.com/files/miscellaneous/foto_no_exif+(2).jpg)

**Comment by LunaTheFoxgirl** [comment]
Have told the person responsible for the discord, will be fixed ASAP

**Comment by LunaTheFoxgirl** [comment]
Not solved yet, please don't close the issue. I'll close it when I've solved it.

**Comment by LunaTheFoxgirl** [comment]
The fix has been issued and should be live on the website.
